### ISSUE TITLE
No HP/Unit Flags after restarting mission via Pause Menu

### ISSUE THREAD

**Issue by moben** [chrishayesmu/XCOM-LW-CommunityEdition#46]
After restarting a mission via the pause menu, no HP, blue/yellow move indicators or line-of-sight flags are shown for soldiers or enemies. Saving and reloading works around the issue.

**Comment by chrishayesmu** [comment]
I have no idea why, but when I quit creating unit flags for the invisible sectoid/zombie, this is fixed. I wish I understood it but I do not.

Thanks for the report. If you can't reproduce with https://github.com/chrishayesmu/XCOM-LW-CommunityEdition/commit/34900c84fd8eca97de326ef2b6ff2ab5cafe6d2e, feel free to close.

**Comment by moben** [comment]
Seems to be fixed. For future reference, this also happened sometimes when exiting to the main menu and then starting a new game. Both seems fixed but the second one was inconsistent anyway.
