### ISSUE TITLE
Motion tracker is broken

### ISSUE THREAD

**Issue by moben** [chrishayesmu/XCOM-LW-CommunityEdition#50]
Mainly documenting that I'm looking at this:

The motion tracker currently does nothing in the tac game as far as I can tell.

[here](https://github.com/moben/XCOM-LW-CommunityEdition/commits/wip_motion_tracker) is what I tried so far but I can't get the actual UI element to show yet.

**Comment by chrishayesmu** [comment]
PR merged, thank you!
