### ISSUE TITLE
Wrong hit chances on civilians in terror missions

### ISSUE THREAD

**Issue by moben** [chrishayesmu/XCOM-LW-CommunityEdition#59]
As far as I understand, in base LW aliens are supposed to have a 100% chance to hit civilians. Even debuffs should not lower this chance (I think except suppression, which might be a base game bug).

In the first terror mission in my current test campaign I saw grounded floaters miss civilians (both flanked and in cover). Perfect information showed <100% hit chances.

**Comment by chrishayesmu** [comment]
I very likely missed this in the hit chance rewrites. I'll look at it as soon as my own test campaign reaches a terror, thanks.

**Comment by chrishayesmu** [comment]
PR: https://github.com/chrishayesmu/XCOM-LW-CommunityEdition/pull/62
