### ISSUE TITLE
Defense bonus from smoke does not count when running overwatch

### ISSUE THREAD

**Issue by Fjoggs** [chrishayesmu/XCOM-LW-CommunityEdition#96]
I believe running an overwatch or a suppression inside a smoke does not grant you the 20/40 defense bonus if you're inside a smoke.

Sorry for the low quality issue report :sweat_smile:

**Comment by chrishayesmu** [comment]
Duplicate of https://github.com/chrishayesmu/XCOM-LW-CommunityEdition/issues/27
